[32m2025-04-15 22:19:11 +0000[0m - dagster - [34mDEBUG[0m - internal_ml_job - 17209dab-d6d1-44b5-8358-fa949323170c - 4626 - LOGS_CAPTURED - Started capturing logs in process (pid: 4626).
[32m2025-04-15 22:19:11 +0000[0m - dagster - [34mDEBUG[0m - internal_ml_job - 17209dab-d6d1-44b5-8358-fa949323170c - 4626 - internal_calculate_cluster_metrics - STEP_START - Started execution of step "internal_calculate_cluster_metrics".
[32m2025-04-15 22:19:11 +0000[0m - dagster - [34mDEBUG[0m - internal_ml_job - 17209dab-d6d1-44b5-8358-fa949323170c - internal_calculate_cluster_metrics - Loading file from: storage/internal_assign_clusters using PickledObjectFilesystemIOManager...
[32m2025-04-15 22:19:11 +0000[0m - dagster - [34mDEBUG[0m - internal_ml_job - 17209dab-d6d1-44b5-8358-fa949323170c - 4626 - internal_calculate_cluster_metrics - LOADED_INPUT - Loaded input "internal_assign_clusters" using input manager "io_manager", from output "result" of step "internal_assign_clusters"
[32m2025-04-15 22:19:11 +0000[0m - dagster - [34mDEBUG[0m - internal_ml_job - 17209dab-d6d1-44b5-8358-fa949323170c - internal_calculate_cluster_metrics - Loading file from: storage/internal_train_clustering_models using PickledObjectFilesystemIOManager...
[32m2025-04-15 22:19:11 +0000[0m - dagster - [34mDEBUG[0m - internal_ml_job - 17209dab-d6d1-44b5-8358-fa949323170c - 4626 - internal_calculate_cluster_metrics - LOADED_INPUT - Loaded input "internal_train_clustering_models" using input manager "io_manager", from output "result" of step "internal_train_clustering_models"
[32m2025-04-15 22:19:11 +0000[0m - dagster - [34mDEBUG[0m - internal_ml_job - 17209dab-d6d1-44b5-8358-fa949323170c - 4626 - internal_calculate_cluster_metrics - STEP_INPUT - Got input "internal_assign_clusters" of type "Dict[String,DataFrame]". (Type check passed).
[32m2025-04-15 22:19:11 +0000[0m - dagster - [34mDEBUG[0m - internal_ml_job - 17209dab-d6d1-44b5-8358-fa949323170c - 4626 - internal_calculate_cluster_metrics - STEP_INPUT - Got input "internal_train_clustering_models" of type "Dict[String,Any]". (Type check passed).
[32m2025-04-15 22:19:11 +0000[0m - dagster - [34mDEBUG[0m - internal_ml_job - 17209dab-d6d1-44b5-8358-fa949323170c - 4626 - internal_calculate_cluster_metrics - STEP_OUTPUT - Yielded output "result" of type "Dict[String,Any]". (Type check passed).
[32m2025-04-15 22:19:11 +0000[0m - dagster - [34mDEBUG[0m - internal_ml_job - 17209dab-d6d1-44b5-8358-fa949323170c - internal_calculate_cluster_metrics - Writing file at: storage/internal_calculate_cluster_metrics using PickledObjectFilesystemIOManager...
Exception while writing logger call to event log: (sqlite3.DatabaseError) file is not a database
[SQL: INSERT INTO event_logs (run_id, event, dagster_event_type, timestamp, step_key, asset_key, partition) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('17209dab-d6d1-44b5-8358-fa949323170c', '{"__class__": "EventLogEntry", "dagster_event": {"__class__": "DagsterEvent", "event_specific_data": {"__class__": "StepMaterializationData", "asset_ ... (2201 characters truncated) ... key": "internal_calculate_cluster_metrics", "timestamp": 1744755551.917589, "user_message": "Materialized value internal_calculate_cluster_metrics."}', 'ASSET_MATERIALIZATION', '2025-04-15 22:19:11.917589', 'internal_calculate_cluster_metrics', '["internal_calculate_cluster_metrics"]', None)]
(Background on this error at: https://sqlalche.me/e/14/4xp6)
Exception while writing logger call to event log: (sqlite3.DatabaseError) file is not a database
[SQL: INSERT INTO event_logs (run_id, event, dagster_event_type, timestamp, step_key, asset_key, partition) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('17209dab-d6d1-44b5-8358-fa949323170c', '{"__class__": "EventLogEntry", "dagster_event": {"__class__": "DagsterEvent", "event_specific_data": {"__class__": "StepFailureData", "error": {"__cl ... (7956 characters truncated) ... nal_calculate_cluster_metrics", "timestamp": 1744755551.960164, "user_message": "Execution of step \\"internal_calculate_cluster_metrics\\" failed."}', 'STEP_FAILURE', '2025-04-15 22:19:11.960164', 'internal_calculate_cluster_metrics', None, None)]
(Background on this error at: https://sqlalche.me/e/14/4xp6)
